# Generated by Django 5.0.6 on 2024-06-06 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('14781763-5570-43f6-bad3-b75ba14064f5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
