# Generated by Django 5.0.6 on 2024-06-06 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_basemodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e2002e4e-5081-4a1b-9c4d-830a99cabadf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
