# Generated by Django 5.0.6 on 2024-05-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_productsigns_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productsigns',
            table='product_signs',
        ),
    ]
