# Generated by Django 5.0.6 on 2024-05-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_data_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='image',
        ),
    ]
